import "./globals.css";
import { Providers } from "./providers";
import { UserProvider } from "./context/userContext";

export const metadata = {
  title: "Github user Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Providers>{children}</Providers>
        </UserProvider>
      </body>
    </html>
  );
}
